### ISSUE TITLE
ModelToModel Distance Output Mesh doesnot have same topology as the VTKFile1

### ISSUE THREAD

**Issue by ShusilDangi** [NIRALUser/3DMetricTools#3]
Number of points (and cells) in the output vtk model is not the same as input vtkfile1.
Doesn't match the description https://www.slicer.org/wiki/Documentation/4.6/Extensions/ModelToModelDistance

**Comment by allemangD** [comment]
I'm unable to reproduce this in the latest version. Since the issue is so old, and I am unable to reproduce, I'm closing.

Please re-open or create a new issue if this is still a problem. It would be helpful to include some sample data which produces the problem.
