### ISSUE TITLE
Extension failing to build 

### ISSUE THREAD

**Issue by bpaniagua** [NIRALUser/3DMetricTools#8]
Model to model distance extension is not building[ in the preview version of Slicer](http://slicer.cdash.org/buildSummary.php?buildid=1747504). 

Additionally, the  extension is currently building from @jcfr [fork](https://github.com/Slicer/ExtensionsIndex/blob/master/ModelToModelDistance.s4ext#L9), is there a reason for that? 

In the stable version there is a library problem

`Model To Model Distance standard error:

dyld: Library not loaded: /Volumes/Dashboards/Support/qt-everywhere-build-5.10.0/lib/QtSql.framework/Versions/5/QtSql
  Referenced from: /Applications/Slicer.app/Contents/Extensions-28257/ModelToModelDistance/lib/Slicer-4.10/cli-modules/libModelToModelDistanceLib.dylib
  Reason: image not found`

cc: @jcfr @sjh26 @vicory @juanprietob

**Comment by juanprietob** [comment]
Was this command removed from cmake? I'm not sure where this error is coming from
> Unknown CMake command "check_c_compiler_flag"

**Comment by bpaniagua** [comment]
Are you compiling in Linux?

**Comment by lassoan** [comment]
> Was this command removed from cmake? I'm not sure where this error is coming from
> 
> > Unknown CMake command "check_c_compiler_flag"

Probably you just need to include the CMake module where this function is defined:

    include(CheckCCompilerFlag)

Previously CheckCCompilerFlag might have been indirectly pulled in by some other included CMake file, so things still worked despite the missing include.

**Comment by jcfr** [comment]
The function `check_c_compiler_flag` is provided by the CMake module `CheckCCompilerFlag`

It turns out that with the ITK update, modules like `ITK_CheckCCompilerFlag` have been updated.

I will push a fix in shortly.

**Comment by jcfr** [comment]
Fixed in 3DMetricTools and ShapePopulationViewer projects:
* https://github.com/NIRALUser/3DMetricTools/pull/9
* https://github.com/NIRALUser/ShapePopulationViewer/pull/46

**Comment by jcfr** [comment]
Note: If there are no objections, I will merge the changes later this afternoon and update the extension description files.

**Comment by jcfr** [comment]
Closing. Changes integrated and ExtensionsIndex updated.
